package com.auf.activity

const val KEEP_ME_LOGIN = "KEY_KEEP_LOGGED_IN"
const val USER_NAME = "KEY_USER_NAME"
const val USER_PASSWORD = "KEY_USER_PASSWORD"
const val USER_FIRST_NAME = "KEY_USER_FIRST_NAME"
const val USER_LAST_NAME = "KEY_USER_LAST_NAME"
const val USER_AGE = "KEY_USER_AGE"
const val USER_GENDER = "KEY_USER_GENDER"